
/** Component:
* 
* @name Zauberer
*
* @Components	Position	(standard)
*				Rotation	()
*				Scale		()
*
* @Properties	Vector3f Position	(autogenerated)
*				Vector3f Rotation
*				float	 Scale
*/

//Used engine classes
namespace EntitySystem {
	class Preset;
	class IComponentArgs;
}

//Autogenerated
class ZaubererBase {

};

//User managed
class Zauberer {

};